import { makeEvent, type ContextEvent, type EventType, type Importance } from '../../core/events.js';
import { contentHash, sha256 } from '../../core/ids.js';
import type { Adapter, AdapterContext, AdapterSurface, InstructionFile, TranslateResult } from '../types.js';
import { candidatesIn } from '../discover.js';
import { claudeHookInstaller, claudeProjectDir } from './hooks.js';
import { claudeMcp } from './mcp.js';
import { claudeNativeMemory } from './memory.js';

/**
 * Claude Code adapter.
 *
 * PRD 39 suggests wrapping the agent process. In practice Claude Code already exposes two
 * non-invasive surfaces - lifecycle hooks and the JSONL transcript - and using them means
 * no PTY interception, no changes to the agent, and it satisfies PRD 54.7 ("no changes to
 * the main model") literally. Hooks give low latency, the transcript gives completeness;
 * both paths emit the same dedupe hash so the overlap costs nothing.
 */

/** Tools whose successful use means a file on disk changed. */
const WRITE_TOOLS = new Set(['Write', 'Edit', 'MultiEdit', 'NotebookEdit']);
const SHELL_TOOLS = new Set(['Bash', 'BashOutput']);

/** Wrapper text Claude Code injects into user turns that is not the user speaking. */
const INJECTED_BLOCK =
  /^\s*<(?:ide_opened_file|ide_selection|system-reminder|command-name|command-message|command-args|local-command-stdout|local-command-caveat|user-prompt-submit-hook)\b/;

/** The same tags, to be excised wherever they appear rather than only at the start. */
const SCAFFOLD_TAGS = [
  'ide_opened_file',
  'ide_selection',
  'system-reminder',
  'command-name',
  'command-message',
  'command-args',
  'local-command-stdout',
  'local-command-caveat',
  'user-prompt-submit-hook',
  'task-notification',
];

/**
 * Harness text that carries instructions but is not the user speaking.
 *
 * These have no tag to strip: the resume preamble after a compaction reads exactly like a user
 * message, and a real session turned "do not acknowledge the summary, do not recap" into a
 * `source: user` + `critical` constraint - which `isProtected` then made permanent. Session
 * scaffolding must never reach the most privileged tier of memory.
 */
const HARNESS_PREAMBLE = [
  /this session is being continued from a previous conversation/i,
  /your response above was cut off mid-stream/i,
  /the messages below were generated by the user while running local commands/i,
  /please continue the conversation from where we left (?:it )?off/i,
  /\bhook is now active with condition\b/i,
  /^\s*caveat:/i,
  /\bsystem notification\b.*\bnot user input\b/i,
  /\bthis is an automated background-task event\b/i,
];

/**
 * Instructions to the agent that can appear anywhere in a turn, including deep inside a
 * compaction summary that also quotes what the user really said.
 *
 * Removed line by line rather than by discarding the turn: scanning the whole text for a preamble
 * marker did stop "do not acknowledge the summary" becoming a protected constraint, but it also
 * threw away the original project goal, which existed only as a quotation inside that summary.
 */
const HARNESS_INSTRUCTION_LINE = [
  /\bdo not acknowledge the summary\b/i,
  /\bdo not recap\b/i,
  /\bresume directly from where it stops\b/i,
  /\bcontinue the conversation from where it left off\b/i,
  /\bdo not respond to (?:these|those) messages\b/i,
  /\bif you need specific details from before compaction\b/i,
  /\bthe summary below covers the earlier portion of the conversation\b/i,
  /\bno apology, no recap\b/i,
];

/**
 * Remove scaffolding from a user turn, returning what the user actually said.
 *
 * Excising rather than rejecting matters: the scaffolding is often appended to a real message,
 * and rejecting the whole turn would lose the user's own words with it.
 */
export function stripHarnessScaffolding(text: string): string {
  let out = text;
  for (const tag of SCAFFOLD_TAGS) {
    out = out.replace(new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?</${tag}>`, 'gi'), ' ');
    // An unterminated block runs to the end of the turn; nothing after it is the user either.
    out = out.replace(new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*$`, 'i'), ' ');
  }
  // Instruction lines go wherever they appear, so a summary that also quotes the user keeps the
  // quotation and loses the imperative.
  out = out
    .split('\n')
    .filter((line) => !HARNESS_INSTRUCTION_LINE.some((p) => p.test(line)))
    .join('\n')
    .trim();

  // A turn that *opens* with harness framing is framing all the way down; those are dropped
  // whole. Judged on the opening only, because a marker quoted later may sit beside real content.
  if (HARNESS_PREAMBLE.some((p) => p.test(out.slice(0, 600)))) return '';
  return out;
}

interface ContentBlock {
  type?: string;
  text?: string;
  thinking?: string;
  name?: string;
  id?: string;
  input?: unknown;
  tool_use_id?: string;
  content?: unknown;
  is_error?: boolean;
}

export class ClaudeAdapter implements Adapter {
  readonly name = 'claude';
  readonly agent = 'Claude Code';

  readonly surfaces: readonly AdapterSurface[] = [
    {
      kind: 'hook',
      preferred: true,
      installable: true,
      description:
        'Lifecycle hooks in .claude/settings.json. Synchronous for the agent, so the handler ingests and exits without calling a model.',
      hooks: claudeHookInstaller,
    },
    {
      kind: 'transcript',
      preferred: false,
      installable: true,
      description: 'JSONL transcript under ~/.claude/projects/<slugged-cwd>/. Complete, tailed from a byte cursor.',
      locate: (projectRoot, home) => candidatesIn(claudeProjectDir(home, projectRoot)),
    },
  ];

  readonly mcp = claudeMcp;

  readonly instructionFiles: readonly InstructionFile[] = [
    {
      target: 'claude-local',
      path: 'CLAUDE.local.md',
      description: 'Personal project instructions Claude Code loads every session; gitignored by convention',
    },
  ];

  readonly nativeMemory = claudeNativeMemory;

  /** Only `Stop` marks a finished turn whose usage is now written to the transcript. */
  usageSource(hookPayload: unknown): string | null {
    if (!hookPayload || typeof hookPayload !== 'object') return null;
    const p = hookPayload as Record<string, unknown>;
    if (p.hook_event_name !== 'Stop') return null;
    return typeof p.transcript_path === 'string' ? p.transcript_path : null;
  }

  translate(raw: unknown, ctx: AdapterContext): TranslateResult {
    if (!raw || typeof raw !== 'object') return { events: [] };
    const rec = raw as Record<string, unknown>;

    // Hook payloads carry hook_event_name; transcript records carry type.
    if (typeof rec.hook_event_name === 'string') return this.fromHook(rec, ctx);
    return this.fromTranscript(rec, ctx);
  }

  // ------------------------------------------------------------------- hooks

  private fromHook(rec: Record<string, unknown>, ctx: AdapterContext): TranslateResult {
    const hook = String(rec.hook_event_name);
    const sessionId = str(rec.session_id) ?? ctx.sessionId;
    const cwd = str(rec.cwd) ?? ctx.cwd ?? null;
    const base = { session_id: sessionId, source: this.name, cwd };
    const events: ContextEvent[] = [];

    const push = (type: EventType, payload: Record<string, unknown>, importance?: Importance) => {
      events.push(
        makeEvent({
          session_id: base.session_id,
          source: base.source,
          timestamp: new Date().toISOString(),
          type,
          payload,
          ordinal: ctx.ordinal ?? null,
          ...(importance ? { importance } : {}),
          dedupe_hash: contentHash(['claude-hook', sessionId, hook, payload]),
        }),
      );
    };

    switch (hook) {
      case 'SessionStart':
        push('SESSION_STARTED', { project: cwd ? basename(cwd) : null, cwd, source: str(rec.source) });
        break;

      case 'UserPromptSubmit': {
        const prompt = str(rec.prompt);
        const said = prompt && !INJECTED_BLOCK.test(prompt) ? stripHarnessScaffolding(prompt) : '';
        if (said) push('USER_MESSAGE', { text: said });
        break;
      }

      case 'PostToolUse': {
        const tool = str(rec.tool_name) ?? 'unknown';
        const input = rec.tool_input as Record<string, unknown> | undefined;
        const response = rec.tool_response;
        const output = stringifyToolContent(response);
        if (SHELL_TOOLS.has(tool)) {
          push('COMMAND_EXECUTED', {
            tool,
            command: str(input?.command),
            output,
            exit_code: inferExitCode(response, output),
          });
        } else if (WRITE_TOOLS.has(tool)) {
          const path = str(input?.file_path) ?? str(input?.notebook_path);
          if (path) push('FILE_CHANGED', { tool, path, content_hash: hashOfEditedContent(input) });
        } else {
          push('TOOL_RESULT', { tool, output, args: redactArgs(input) });
        }
        break;
      }

      case 'PreCompact':
        // The agent is about to compact: flush everything we know first (PRD 24).
        push('COMPACTION_REQUESTED', { trigger: str(rec.trigger) ?? 'unknown' }, 'high');
        break;

      case 'Stop':
      case 'SubagentStop':
        // The end of a *turn*, not of a task. Emitting TASK_COMPLETED here would have the fold
        // mark the working task done after every reply. What Stop does carry is a finished
        // turn's token usage, read from the transcript by `usageSource`.
        break;

      case 'SessionEnd':
        push('SESSION_ENDED', { reason: str(rec.reason) });
        break;

      default:
        break;
    }

    return { events, session: { id: sessionId, cwd, agent: 'claude-code' } };
  }

  // -------------------------------------------------------------- transcript

  private fromTranscript(rec: Record<string, unknown>, ctx: AdapterContext): TranslateResult {
    const type = str(rec.type);
    const sessionId = str(rec.sessionId) ?? ctx.sessionId;
    const cwd = str(rec.cwd) ?? ctx.cwd ?? null;
    const ts = str(rec.timestamp) ?? new Date().toISOString();
    const uuid = str(rec.uuid) ?? String(ctx.ordinal ?? 0);
    const events: ContextEvent[] = [];
    // Only claim a session when the record actually named one. Falling back to the caller's
    // id here would conjure a phantom session row for every bookkeeping record.
    const result: TranslateResult = str(rec.sessionId)
      ? { events, session: { id: sessionId, cwd, agent: 'claude-code' } }
      : { events };

    // Sidechain records are subagent traffic; the parent session already records the
    // delegation, so ingesting both would double-count.
    if (rec.isSidechain === true) return result;

    const push = (
      etype: EventType,
      payload: Record<string, unknown>,
      key: string,
      importance?: Importance,
    ) => {
      events.push(
        makeEvent({
          session_id: sessionId,
          source: this.name,
          timestamp: ts,
          type: etype,
          payload,
          ordinal: ctx.ordinal ?? null,
          ...(importance ? { importance } : {}),
          dedupe_hash: contentHash(['claude-transcript', sessionId, uuid, key]),
        }),
      );
    };

    if (type === 'user') {
      const blocks = messageBlocks(rec);
      for (const [n, b] of blocks.entries()) {
        if (b.type === 'tool_result') {
          const output = stringifyToolContent(b.content);
          push(
            b.is_error ? 'ERROR_DETECTED' : 'TOOL_RESULT',
            { tool_use_id: b.tool_use_id, output, ...(b.is_error ? { error: output } : {}) },
            `tool_result:${n}`,
          );
        } else if (b.type === 'text' && b.text) {
          if (INJECTED_BLOCK.test(b.text)) continue;
          const said = stripHarnessScaffolding(b.text);
          if (!said) continue;
          push('USER_MESSAGE', { text: said }, `text:${n}`);
        }
      }
      return result;
    }

    if (type === 'assistant') {
      const msg = rec.message as Record<string, unknown> | undefined;
      const blocks = messageBlocks(rec);
      for (const [n, b] of blocks.entries()) {
        if (b.type === 'text' && b.text) {
          push('ASSISTANT_MESSAGE', { text: b.text }, `text:${n}`);
        } else if (b.type === 'tool_use') {
          const tool = b.name ?? 'unknown';
          const input = (b.input ?? {}) as Record<string, unknown>;
          if (SHELL_TOOLS.has(tool)) {
            push('TOOL_CALL', { tool, command: str(input.command), tool_use_id: b.id }, `tool_use:${n}`);
          } else if (WRITE_TOOLS.has(tool)) {
            const path = str(input.file_path) ?? str(input.notebook_path);
            if (path) {
              push(
                'FILE_CHANGED',
                { tool, path, content_hash: hashOfEditedContent(input), tool_use_id: b.id },
                `tool_use:${n}`,
              );
            }
          } else {
            push('TOOL_CALL', { tool, args: redactArgs(input), tool_use_id: b.id }, `tool_use:${n}`);
          }
        }
        // `thinking` blocks are intentionally not ingested: they are the model's scratch
        // space, exactly the "temporary information" PRD 2 wants kept out of memory.
      }
      const usage = msg?.usage as Record<string, number> | undefined;
      if (usage) {
        result.agentUsage = {
          input_tokens: usage.input_tokens ?? 0,
          output_tokens: usage.output_tokens ?? 0,
          cache_read_input_tokens: usage.cache_read_input_tokens ?? 0,
          cache_creation_input_tokens: usage.cache_creation_input_tokens ?? 0,
          model: str(msg?.model),
          message_id: str(msg?.id),
        };
      }
      return result;
    }

    if (type === 'queue-operation' && str(rec.operation) === 'enqueue') {
      const content = str(rec.content);
      const said = content && !INJECTED_BLOCK.test(content) ? stripHarnessScaffolding(content) : '';
      if (said) {
        push('USER_MESSAGE', { text: said }, 'queued_prompt');
      }
      return result;
    }

    return result;
  }
}

// ------------------------------------------------------------------- helpers

function messageBlocks(rec: Record<string, unknown>): ContentBlock[] {
  const msg = rec.message as Record<string, unknown> | undefined;
  const content = msg?.content;
  if (typeof content === 'string') return [{ type: 'text', text: content }];
  if (Array.isArray(content)) return content as ContentBlock[];
  return [];
}

function str(v: unknown): string | null {
  return typeof v === 'string' && v.length > 0 ? v : null;
}

function basename(p: string): string {
  const parts = p.replace(/\/+$/, '').split('/');
  return parts[parts.length - 1] ?? p;
}

export function stringifyToolContent(content: unknown): string {
  if (content == null) return '';
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content
      .map((c) => {
        if (typeof c === 'string') return c;
        if (c && typeof c === 'object') {
          const o = c as Record<string, unknown>;
          if (typeof o.text === 'string') return o.text;
          if (typeof o.content === 'string') return o.content;
        }
        return '';
      })
      .filter(Boolean)
      .join('\n');
  }
  if (typeof content === 'object') {
    const o = content as Record<string, unknown>;
    const parts: string[] = [];
    // An empty string is still a string: returning `stdout: ""` early meant every command
    // that failed and wrote only to stderr arrived with no output at all, so the fold saw
    // nothing to explain and filed a real test failure as noise.
    for (const key of ['stdout', 'output', 'text', 'content', 'result']) {
      const v = o[key];
      if (typeof v === 'string' && v.trim().length > 0) {
        parts.push(v);
        break;
      }
    }
    const stderr = typeof o.stderr === 'string' ? o.stderr : '';
    // Both, when both are present: a failing build routinely splits its message across them.
    if (stderr.trim().length > 0) parts.push(stderr);
    if (parts.length > 0) return parts.join('\n');
    return JSON.stringify(content).slice(0, 8000);
  }
  return String(content);
}

/** Claude Code does not report an exit status directly; infer it from the response shape. */
export function inferExitCode(response: unknown, output: string): number | undefined {
  if (response && typeof response === 'object') {
    const o = response as Record<string, unknown>;
    if (typeof o.exit_code === 'number') return o.exit_code;
    if (typeof o.exitCode === 'number') return o.exitCode;
    if (o.is_error === true || o.isError === true) return 1;
    if (typeof o.interrupted === 'boolean' && o.interrupted) return 130;
  }
  if (/^\s*(command failed|error:)/i.test(output)) return 1;
  // Claude's Bash reports success as `{stdout, stderr, interrupted: false}` with no exit code at
  // all; a failure arrives as an error instead. Leaving that undefined made every successful
  // command unknowable, so a `git commit` could never count as having happened.
  if (response && typeof response === 'object') {
    const o = response as Record<string, unknown>;
    if ('stdout' in o && o.interrupted === false) return 0;
  }
  return undefined;
}

/**
 * A fingerprint of what a write produced, so an identical rewrite is recognised as a no-op
 * (PRD 51 "IF file unchanged, don't re-index").
 */
function hashOfEditedContent(input: Record<string, unknown> | undefined): string | null {
  if (!input) return null;
  const parts: string[] = [];
  for (const key of ['content', 'new_string', 'new_source']) {
    const v = input[key];
    if (typeof v === 'string') parts.push(v);
  }
  if (Array.isArray(input.edits)) {
    for (const e of input.edits) {
      const o = e as Record<string, unknown>;
      if (typeof o?.new_string === 'string') parts.push(o.new_string);
    }
  }
  return parts.length > 0 ? sha256(parts.join('')) : null;
}

/** Tool arguments can be large; keep the shape, drop the bulk. */
function redactArgs(input: unknown): unknown {
  if (!input || typeof input !== 'object') return input;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(input as Record<string, unknown>)) {
    if (typeof v === 'string' && v.length > 500) out[k] = `${v.slice(0, 500)}...[${v.length} chars]`;
    else out[k] = v;
  }
  return out;
}

export const claudeAdapter = new ClaudeAdapter();
