import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, extname, isAbsolute, relative, resolve } from 'node:path';
import {
  ADAPTERS,
  findInstructionFile,
  instructionFiles,
  type HostEnv,
  type InstructionFile,
  type InstructionFormat,
} from '../adapters/index.js';
import { extractBlock, removeBlock, upsertBlock, type Markers } from '../core/markers.js';
import { getMeta, setMeta } from '../store/db.js';
import { absoluteTime, type BuiltContext } from '../retrieval/context-builder.js';
import type { ContextManager } from '../daemon/manager.js';

/**
 * `contextd mirror` - the bootstrap, copied into an instruction file the agent already reads.
 *
 * For an agent with neither hooks nor MCP this is the only way memory reaches it. Writing the
 * block is serving (invariant 30): the agent will read what was written, so it goes through
 * `serveBootstrap` and is logged - under `(mirror)`, not `(bootstrap)`, because the Benefits view
 * counts `(bootstrap)` rows as session resumes and one write is read by an unknown number of them.
 * `--check` only measures, through `bootstrapContext`, and logs nothing.
 *
 * Times are absolute in the copy: "recorded 3h ago" is true only when rendered, and a file is
 * read days later. That also makes the rendering a pure function of state, which is what lets
 * `--check` compare it.
 *
 * Each agent's file has its own budget and format (`InstructionFile`): the agent pays for the
 * whole file on every turn, so the bootstrap is built to that budget by the context builder -
 * sections shrink and drop whole items, the text is never truncated - and a Cursor rule is
 * created with the frontmatter that makes Cursor load it.
 */

export const MIRROR_MARKERS: Markers = {
  start: '<!-- contextd:start -->',
  end: '<!-- contextd:end -->',
};

export const MIRROR_LABEL = '(mirror)';

/** Absolute paths `mirror` has written, so `uninstall` and maintenance find them again. */
const TARGETS_META = 'mirror_targets';

/** Where a mirror goes, and how it is framed and budgeted there. */
export interface MirrorTarget {
  path: string;
  format: InstructionFormat;
  /** Token budget for the bootstrap; null means the configured bootstrap budget. */
  budget: number | null;
  /** The declared instruction file, when the target is one. */
  declared: InstructionFile | null;
}

/** A declared target name, an adapter name, or a path, as an absolute path. */
export function resolveMirrorTarget(target: string, projectRoot: string): string {
  const declared = findInstructionFile(target);
  const adapter = ADAPTERS[target];
  if (!declared && adapter) {
    // Otherwise `--target opencode` would quietly create a file called "opencode".
    throw new Error(`${adapter.agent} declares no instruction file of its own; see \`contextd surfaces\` for the targets`);
  }
  const path = declared ? declared.path : target;
  return isAbsolute(path) ? path : resolve(projectRoot, path);
}

/**
 * Everything about a target. A path that is some agent's declared file gets that file's budget
 * and format, so `--target .cursor/rules/contextd.mdc` and `--target cursor` write the same
 * thing - and so does a maintenance refresh, which only remembers paths.
 */
export function mirrorTarget(target: string, projectRoot: string, opts: { budget?: number } = {}): MirrorTarget {
  const path = resolveMirrorTarget(target, projectRoot);
  const declared = instructionFiles().find((f) => resolve(projectRoot, f.path) === path) ?? null;
  const format: InstructionFormat = declared?.format ?? (extname(path) === '.mdc' ? 'mdc' : 'markdown');
  return { path, format, budget: opts.budget ?? declared?.budget ?? null, declared };
}

/**
 * The frontmatter a Cursor rule file `mirror` creates starts with. Without `alwaysApply: true`
 * Cursor attaches a rule only when asked for it, which for project memory means never. Written
 * only into a file `mirror` creates: in an existing rule, the frontmatter is the person's.
 */
export const MDC_FRONTMATTER = [
  '---',
  'description: Project memory maintained by contextd (`contextd mirror`)',
  'alwaysApply: true',
  '---',
  '',
].join('\n');

function header(generatedAt: string, version: number): string {
  return [
    '<!-- Generated by `contextd mirror` from project memory. Anything between the contextd markers is overwritten. -->',
    `> Project memory (contextd), generated ${absoluteTime(generatedAt)} from state v${version}. ` +
      'Refresh with `contextd mirror`; check with `contextd mirror --check`.',
  ].join('\n');
}

function body(built: BuiltContext): string {
  return built.text.length > 0 ? built.text : '_No project memory recorded yet._';
}

/** The body inside an existing block: everything after the header's comment and quote lines. */
function bodyOf(inner: string): string {
  const lines = inner.replace(/^\n+/, '').split('\n');
  let n = 0;
  while (n < lines.length && (lines[n]!.startsWith('<!--') || lines[n]!.startsWith('>') || lines[n]!.trim() === '')) n += 1;
  return lines.slice(n).join('\n').trim();
}

export interface MirrorCheck {
  path: string;
  exists: boolean;
  hasBlock: boolean;
  stale: boolean;
  reason: string;
}

function targetOf(manager: ContextManager, target: string | MirrorTarget): MirrorTarget {
  return typeof target === 'string' ? mirrorTarget(target, manager.projectRoot) : target;
}

function buildOptions(t: MirrorTarget): { absoluteTimes: true; budget?: number } {
  return { absoluteTimes: true, ...(t.budget != null ? { budget: t.budget } : {}) };
}

/** Measure only: nothing is logged, nothing written. */
export function checkMirror(manager: ContextManager, target: string | MirrorTarget): MirrorCheck {
  const t = targetOf(manager, target);
  const { path } = t;
  if (!existsSync(path)) return { path, exists: false, hasBlock: false, stale: true, reason: 'file does not exist' };
  const inner = extractBlock(readFileSync(path, 'utf8'), MIRROR_MARKERS);
  if (inner == null) return { path, exists: true, hasBlock: false, stale: true, reason: 'no contextd block in the file' };
  const expected = body(manager.bootstrapContext(buildOptions(t))).trim();
  const stale = bodyOf(inner) !== expected;
  return { path, exists: true, hasBlock: true, stale, reason: stale ? 'memory changed since it was written' : 'up to date' };
}

export interface MirrorWrite {
  path: string;
  created: boolean;
  changed: boolean;
  tokens: number;
  /** The budget the bootstrap was built to, and how many items it left out to fit. */
  budget: number;
  omitted: number;
}

/**
 * Write (or refresh) the block, replacing only what is between the markers. An unchanged body is
 * not rewritten and not served again - nothing new reached the agent.
 */
export function writeMirror(
  manager: ContextManager,
  target: string | MirrorTarget,
  now = new Date().toISOString(),
): MirrorWrite {
  const t = targetOf(manager, target);
  const { path } = t;
  const created = !existsSync(path);
  const before = created ? '' : readFileSync(path, 'utf8');
  const current = extractBlock(before, MIRROR_MARKERS);
  const measured = manager.bootstrapContext(buildOptions(t));
  const omitted = (b: BuiltContext) => b.sections.reduce((n, s) => n + s.dropped, 0);
  if (current != null && bodyOf(current) === body(measured).trim()) {
    rememberTarget(manager, path);
    return { path, created: false, changed: false, tokens: measured.tokens, budget: measured.budget, omitted: omitted(measured) };
  }
  const served = manager.serveBootstrap(null, { ...buildOptions(t), label: MIRROR_LABEL });
  const inner = `${header(now, manager.store.stateVersion())}\n\n${body(served)}`;
  const base = created && t.format === 'mdc' ? MDC_FRONTMATTER : before;
  if (created) mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, upsertBlock(base, MIRROR_MARKERS, inner), 'utf8');
  rememberTarget(manager, path);
  if (created) remember(manager, CREATED_META, path);
  return { path, created, changed: true, tokens: served.tokens, budget: served.budget, omitted: omitted(served) };
}

/**
 * Remove the block. The file itself goes only when `mirror` created it and nothing else was
 * added since: an empty AGENTS.md someone committed is still theirs.
 */
export function removeMirror(path: string, createdByMirror = false): 'removed' | 'deleted' | 'absent' {
  if (!existsSync(path)) return 'absent';
  const next = removeBlock(readFileSync(path, 'utf8'), MIRROR_MARKERS);
  if (next == null) return 'absent';
  // A rule file `mirror` created holds its frontmatter too; with the block gone it is empty.
  const rest = next.trim();
  if (createdByMirror && (rest.length === 0 || rest === MDC_FRONTMATTER.trim())) {
    rmSync(path);
    return 'deleted';
  }
  writeFileSync(path, next, 'utf8');
  return 'removed';
}

/** Files `mirror` created rather than added a block to. */
const CREATED_META = 'mirror_created';

function list(manager: ContextManager, key: string): string[] {
  try {
    const raw = getMeta(manager.store.db, key);
    const parsed = raw ? (JSON.parse(raw) as unknown) : [];
    return Array.isArray(parsed) ? parsed.filter((p): p is string => typeof p === 'string') : [];
  } catch {
    return [];
  }
}

function remember(manager: ContextManager, key: string, path: string): void {
  const current = list(manager, key);
  if (!current.includes(path)) setMeta(manager.store.db, key, JSON.stringify([...current, path]));
}

export function mirrorTargets(manager: ContextManager): string[] {
  return list(manager, TARGETS_META);
}

export function mirrorCreatedFiles(manager: ContextManager): string[] {
  return list(manager, CREATED_META);
}

function rememberTarget(manager: ContextManager, path: string): void {
  remember(manager, TARGETS_META, path);
}

/** Every file that may hold a mirror block: the ones written, plus every declared target. */
export function candidateMirrorFiles(manager: ContextManager): string[] {
  const declared = instructionFiles().map((f) => resolveMirrorTarget(f.target, manager.projectRoot));
  return [...new Set([...mirrorTargets(manager), ...declared])];
}

/** Refresh stale blocks `mirror` wrote before. Never creates a block. */
export function refreshMirrors(manager: ContextManager): string[] {
  const refreshed: string[] = [];
  for (const path of mirrorTargets(manager)) {
    const check = checkMirror(manager, path);
    if (!check.hasBlock || !check.stale) continue;
    writeMirror(manager, path);
    refreshed.push(path);
  }
  return refreshed;
}

/**
 * Whether git tracks the file. A generated block in a committed file changes on every refresh,
 * which is noise in every diff - worth a warning, not a refusal.
 */
export function isTrackedByGit(env: HostEnv, path: string): boolean | null {
  const git = env.which?.('git');
  if (!git || !env.exec) return null;
  const rel = relative(env.projectRoot, path);
  if (rel.startsWith('..')) return null;
  const r = env.exec(git, ['ls-files', '--error-unmatch', '--', rel], { cwd: env.projectRoot });
  if (r.status === 0) return true;
  // 1 with "did not match" is "untracked"; anything else (not a repo, no git) is unknown.
  return r.status === 1 && /did not match/i.test(r.stderr) ? false : null;
}
