import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { isAbsolute, relative, resolve } from 'node:path';
import { instructionFiles, type HostEnv, type InstructionFile } from '../adapters/index.js';
import { extractBlock, removeBlock, upsertBlock, type Markers } from '../core/markers.js';
import { getMeta, setMeta } from '../store/db.js';
import { absoluteTime, type BuiltContext } from '../retrieval/context-builder.js';
import type { ContextManager } from '../daemon/manager.js';

/**
 * `contextd mirror` - the bootstrap, copied into an instruction file the agent already reads.
 *
 * For an agent with neither hooks nor MCP this is the only way memory reaches it. Writing the
 * block is serving (invariant 30): the agent will read what was written, so it goes through
 * `serveBootstrap` and is logged - under `(mirror)`, not `(bootstrap)`, because the Benefits view
 * counts `(bootstrap)` rows as session resumes and one write is read by an unknown number of them.
 * `--check` only measures, through `bootstrapContext`, and logs nothing.
 *
 * Times are absolute in the copy: "recorded 3h ago" is true only when rendered, and a file is
 * read days later. That also makes the rendering a pure function of state, which is what lets
 * `--check` compare it.
 */

export const MIRROR_MARKERS: Markers = {
  start: '<!-- contextd:start -->',
  end: '<!-- contextd:end -->',
};

export const MIRROR_LABEL = '(mirror)';

/** Absolute paths `mirror` has written, so `uninstall` and maintenance find them again. */
const TARGETS_META = 'mirror_targets';

export function resolveMirrorTarget(
  target: string,
  projectRoot: string,
  files: readonly InstructionFile[] = instructionFiles(),
): string {
  const declared = files.find((f) => f.target === target);
  const path = declared ? declared.path : target;
  return isAbsolute(path) ? path : resolve(projectRoot, path);
}

function header(generatedAt: string, version: number): string {
  return [
    '<!-- Generated by `contextd mirror` from project memory. Anything between the contextd markers is overwritten. -->',
    `> Project memory (contextd), generated ${absoluteTime(generatedAt)} from state v${version}. ` +
      'Refresh with `contextd mirror`; check with `contextd mirror --check`.',
  ].join('\n');
}

function body(built: BuiltContext): string {
  return built.text.length > 0 ? built.text : '_No project memory recorded yet._';
}

/** The body inside an existing block: everything after the header's comment and quote lines. */
function bodyOf(inner: string): string {
  const lines = inner.replace(/^\n+/, '').split('\n');
  let n = 0;
  while (n < lines.length && (lines[n]!.startsWith('<!--') || lines[n]!.startsWith('>') || lines[n]!.trim() === '')) n += 1;
  return lines.slice(n).join('\n').trim();
}

export interface MirrorCheck {
  path: string;
  exists: boolean;
  hasBlock: boolean;
  stale: boolean;
  reason: string;
}

/** Measure only: nothing is logged, nothing written. */
export function checkMirror(manager: ContextManager, path: string): MirrorCheck {
  if (!existsSync(path)) return { path, exists: false, hasBlock: false, stale: true, reason: 'file does not exist' };
  const inner = extractBlock(readFileSync(path, 'utf8'), MIRROR_MARKERS);
  if (inner == null) return { path, exists: true, hasBlock: false, stale: true, reason: 'no contextd block in the file' };
  const expected = body(manager.bootstrapContext({ absoluteTimes: true })).trim();
  const stale = bodyOf(inner) !== expected;
  return { path, exists: true, hasBlock: true, stale, reason: stale ? 'memory changed since it was written' : 'up to date' };
}

export interface MirrorWrite {
  path: string;
  created: boolean;
  changed: boolean;
  tokens: number;
}

/**
 * Write (or refresh) the block, replacing only what is between the markers. An unchanged body is
 * not rewritten and not served again - nothing new reached the agent.
 */
export function writeMirror(manager: ContextManager, path: string, now = new Date().toISOString()): MirrorWrite {
  const created = !existsSync(path);
  const before = created ? '' : readFileSync(path, 'utf8');
  const current = extractBlock(before, MIRROR_MARKERS);
  const measured = manager.bootstrapContext({ absoluteTimes: true });
  if (current != null && bodyOf(current) === body(measured).trim()) {
    rememberTarget(manager, path);
    return { path, created: false, changed: false, tokens: measured.tokens };
  }
  const served = manager.serveBootstrap(null, { absoluteTimes: true, label: MIRROR_LABEL });
  const inner = `${header(now, manager.store.stateVersion())}\n\n${body(served)}`;
  writeFileSync(path, upsertBlock(before, MIRROR_MARKERS, inner), 'utf8');
  rememberTarget(manager, path);
  if (created) remember(manager, CREATED_META, path);
  return { path, created, changed: true, tokens: served.tokens };
}

/**
 * Remove the block. The file itself goes only when `mirror` created it and nothing else was
 * added since: an empty AGENTS.md someone committed is still theirs.
 */
export function removeMirror(path: string, createdByMirror = false): 'removed' | 'deleted' | 'absent' {
  if (!existsSync(path)) return 'absent';
  const next = removeBlock(readFileSync(path, 'utf8'), MIRROR_MARKERS);
  if (next == null) return 'absent';
  if (createdByMirror && next.trim().length === 0) {
    rmSync(path);
    return 'deleted';
  }
  writeFileSync(path, next, 'utf8');
  return 'removed';
}

/** Files `mirror` created rather than added a block to. */
const CREATED_META = 'mirror_created';

function list(manager: ContextManager, key: string): string[] {
  try {
    const raw = getMeta(manager.store.db, key);
    const parsed = raw ? (JSON.parse(raw) as unknown) : [];
    return Array.isArray(parsed) ? parsed.filter((p): p is string => typeof p === 'string') : [];
  } catch {
    return [];
  }
}

function remember(manager: ContextManager, key: string, path: string): void {
  const current = list(manager, key);
  if (!current.includes(path)) setMeta(manager.store.db, key, JSON.stringify([...current, path]));
}

export function mirrorTargets(manager: ContextManager): string[] {
  return list(manager, TARGETS_META);
}

export function mirrorCreatedFiles(manager: ContextManager): string[] {
  return list(manager, CREATED_META);
}

function rememberTarget(manager: ContextManager, path: string): void {
  remember(manager, TARGETS_META, path);
}

/** Every file that may hold a mirror block: the ones written, plus every declared target. */
export function candidateMirrorFiles(manager: ContextManager): string[] {
  const declared = instructionFiles().map((f) => resolveMirrorTarget(f.target, manager.projectRoot));
  return [...new Set([...mirrorTargets(manager), ...declared])];
}

/** Refresh stale blocks `mirror` wrote before. Never creates a block. */
export function refreshMirrors(manager: ContextManager): string[] {
  const refreshed: string[] = [];
  for (const path of mirrorTargets(manager)) {
    const check = checkMirror(manager, path);
    if (!check.hasBlock || !check.stale) continue;
    writeMirror(manager, path);
    refreshed.push(path);
  }
  return refreshed;
}

/**
 * Whether git tracks the file. A generated block in a committed file changes on every refresh,
 * which is noise in every diff - worth a warning, not a refusal.
 */
export function isTrackedByGit(env: HostEnv, path: string): boolean | null {
  const git = env.which?.('git');
  if (!git || !env.exec) return null;
  const rel = relative(env.projectRoot, path);
  if (rel.startsWith('..')) return null;
  const r = env.exec(git, ['ls-files', '--error-unmatch', '--', rel], { cwd: env.projectRoot });
  if (r.status === 0) return true;
  // 1 with "did not match" is "untracked"; anything else (not a repo, no git) is unknown.
  return r.status === 1 && /did not match/i.test(r.stderr) ? false : null;
}
